#!/bin/sh

# Mount any S3 buckets
bkt=' ' read -a bucket <<< "${AWS_BUCKET}"

if [ ${#bucket[@]} -gt 0 ]
then
  echo "${AWS_KEY}:${AWS_SECRET}" > ~/.passwd-s3fs
  chmod 600 ~/.passwd-s3fs
  mkdir -p /tmp/cache

  for i in "${bucket[@]}"
  do
    mkdir -p $AWS_MOUNT_PREFIX/$i
    /usr/local/bin/s3fs -o use_cache=/tmp/cache/$i $i $AWS_MOUNT_PREFIX/$i
    echo "Mounted AWS Bucket: ${AWS_MOUNT_PREFIX}/${i}"
  done
else
  echo "No AWS Mounts"
fi
